#version: "3.9" considéré comme obsolète d'après le terminal

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - ADDRESS=0.0.0.0
      - PORT=8032
    volumes: # on mappe le dossier local à gauche sur le dossier distant dans le volume du container à droite
      - .:/app
      - /app/node_modules
      - /app/build # évite d'écraser le build du container
    command: npm run dev  

  prod:
    build:
      context: .
    ports:
      - "8032:8032"
    environment:
      - NODE_ENV=production